name = "VHTweaksConfigs"
author = "Jrowez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57534fdd62b2a736cacbc29fa5e076153aec4858409c9e54dab496bcbe51502e"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
