name = "VHTweaksConfigs"
author = "Jrowez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d11ce67ff60f9b9a370b1d9eb4a86613671c51d757000442ff0abf57d064c7f9"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
