name = "VHTweaksConfigs"
author = "Jrowez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "080458e7a79e0f92c21e290cb181b193b36a12e123c41c54cc171023adf1af93"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
