
#QOLHunters Configuration
#SOME CHANGES REQUIRE A CLIENT RESTART
["Client-Only Extensions"]
	#Show the Config Button in the Statistics Menu (H)
	"Show Config Button" = true
	#Adds text overlays to the Vault modifiers, e.g. '+10% Damage' or 'Speed +1'
	"Vault Modifier Text Overlays" = true
	#Adds keybinds to craft/forge/reroll in the Bounty Table, Enchanter, Vault Forge, etc
	"Vault Interface Keybinds" = true
	#Improves the Abilities Tab including levelling specializations directly and showing all possible levels/overlevels
	"Better Abilities Tab" = true
	#Show duration in the cooldown overlay while ability is active (only works with abilities which cooldown starts after their duration ends)
	"Ability Duration Overlay" = true
	#Saves and loads current keybinds when you save/load skills in the Skill Altar
	"Skill Altar Save Keybinds" = true
	#Render a timer over Vault Gear items that are on cooldown
	"Show Gear Cooldown Time" = true
	#Allows you to cast multiple abilities with a single keybind
	"Ability Multicast" = true
	#Autoswap to the correct treasure key when you right-click a treasure door with another key as long as the correct key is in your main inventory
	"Treasure Key Swapper" = true
	#Add search box to vault stations
	"Searchable Vault Stations" = true
	#Show alert when equipped vault curio has zero uses
	"Zero Uses Alert" = true
	#Show unlocked research requirements in green color
	"Green Unlocked Researches" = true
	#Adds toggles to prestige selection screen
	"Prestige Toggles" = true
	#Adds roll ranges to resource cards when holding shift
	"Resource Card Roll Range" = true
	#Show raw chests and speed up vault history screen
	"Better Loot Stats" = true
	#Enable item overlay showing VOID/PICKUP/OFF state on magnets.
	"Magnet State Overlay" = true
	#Zoom out further in zoomable vault screens (abilities, talents, researches, vault map).
	"Zoom Out Further" = true
	#Show ⌄ above jewel that would be chosen by identification stand.
	"Autochosen Jewel" = true
	#Show jewel weights that determine which jewel gets chosen by identification stand.
	"Autochosen Weight" = false
	#Require shift to view currently modified gear in artisan station in button tooltips.
	"Artisan Gear Tooltip requires Shift" = false
	#Automatically adjust greed trader offer size based on offer count and available space.
	"Responsive Greed Trader Offers" = true

	["Client-Only Extensions"."Item Chaining"]
		#Automatically open the next booster pack in your inventory after you select a card
		"Chain Booster Packs" = true
		#Automatically open the next jewel pouch in your inventory after you select a jewel
		"Chain Jewel Pouches" = true
		#Drops identified jewels from overstacked pouches instead of weirdly shuffling them in your inv 
		#Debug option - should stay enabled normally.
		"Improved Stacked Jewel Pouch Chaining" = true
		#Automatically select the next antique in your inventory after you open one
		"Chain Antiques" = true

	["Client-Only Extensions"."Better Soul Value Tooltips"]
		#Improves the descriptions of soul values in tooltips when holding SHIFT
		"Enable Better Tooltips" = true
		#Uses shorthand for soul values in tooltips (e.g. 1.4M instead of 1408933)
		"Use Shorthand" = true
		#Use soul shards instead of soul value 
		"Use Soul Shards" = false

	["Client-Only Extensions"."Scavenger Vaults"]
		#Shows the number of scavenger items you have in your inventory
		"Scavenger Inventory Count" = true
		#Highlights current objective scavenger items in your inventory
		"Scavenger Highlighter" = true

	["Client-Only Extensions"."Brazier Vaults"]
		#When should brazier hologram display modifier names.
		#Allowed Values: ALWAYS, NEAR, SHIFT, SHIFT_OR_NEAR
		"Show Modifier Name on Brazier Hologram" = "ALWAYS"
		#When should brazier hologram display modifier descriptions.
		#Allowed Values: ALWAYS, NEAR, SHIFT, SHIFT_OR_NEAR
		"Show Modifier Description on Brazier Hologram" = "ALWAYS"
		#How far should modifier info render when the mode is NEAR.
		#Range: 0 ~ 64
		"Near distance" = 12
		#Make Brazier Hologram larger when you're further away to make it readable
		"Dynamic Hologram Scale" = true

	["Client-Only Extensions"."Cake Vaults"]
		#Changes the color of the Vault Cake overlay
		#Allowed Values: PINK, BLUE, YELLOW, GREEN
		"Cake Vault Overlay Color" = "PINK"
		#Changes the style of the Vault Cake overlay
		#Allowed Values: VIGNETTE, RADAR
		"Cake Vault Overlay Style" = "VIGNETTE"

	["Client-Only Extensions"."Bingo Vaults"]
		#Changes the opacity (%) of the Bingo Grid background
		#Range: 0 ~ 100
		"Grid Background Opacity" = 50
		#Changes the color of the Bingo Grid completion overlay
		#Allowed Values: RED, BLUE, YELLOW, GREEN, GLORP
		"Grid Completion Color" = "GREEN"
		#Changes the color of the Bingo Grid selection overlay
		#Allowed Values: RED, BLUE, YELLOW, GREEN, GLORP
		"Grid Selection Color" = "YELLOW"

	["Client-Only Extensions"."HUD Positioning"]

		["Client-Only Extensions"."HUD Positioning"."God Objective"]
			#Changes the X offset of the God Objective
			#Defined as % of screen width
			#Range: 0 ~ 100
			"God Objective X Offset" = 0
			#Changes the Y offset of the God Objective
			#Defined as % of screen height
			#Range: 0 ~ 100
			"God Objective Y Offset" = 45

	["Client-Only Extensions"."Shopping Pedestals"]
		#Includes your bartering discount on shopping pedestals
		"Enable Bartering Discount Display" = true
		#Shopping pedestals throw items so that your magnets/bags can pick them up instead
		"Shopping Pedestal Throws Items" = true
		#Treasure pedestals throw items so that your magnets/bags can pick them up instead
		"Treasure Pedestal Throws Items" = true

	["Client-Only Extensions"."Rarity Highlighter"]
		#Enable highlighting Vault Gear in AE and RS while holding <SHIFT>
		"Enable Rarity Highlighter in AE and RS" = true

	#Use a Warped Fungus on a Stick to configure Virtual Dehammerizer.
	#Use arrow UP/DOWN keys to cycle between Dehammerizers.
	#Use Ctrl+RightClick to add a Dehammerizer.
	#Use Ctrl+Delete to remove a Dehammerizer
	["Client-Only Extensions"."Virtual Dehammerizer"]
		#Enable Virtual Dehammerizer
		"Enable Virtual Dehammerizer" = true
		#Virtual Dehammerizer Mode
		#Choose SPHERE for a sphere defined around the chosen block position.
		#Choose CYLINDER to encompass the full height of the map
		#Allowed Values: SPHERE, CYLINDER
		"Dehammerizer Mode" = "SPHERE"
		#Virtual Dehammerizer Range
		#Range: 8 ~ 64
		"Dehammerizer Range" = 24

	["Client-Only Extensions"."Ascension Vaults"]
		#Enable a tooltip to show the amount of Ember granted on a failed Ascension Vault while holding <SHIFT> on Ascension Crystals
		"Ascension Crystal Ember Grant Amount" = true
		#Enable a tooltip to show the amount of Ember granted on a failed Ascension Vault while holding <SHIFT> on Challenger Rocks
		"Challenger Rock Ember Grant Amount" = true

	["Client-Only Extensions"."Hunter Particles"]
		#Show Hunter Particles for Objectives
		Objectives = true
		#Show Hunter Particles for Gilded Chests
		Gilded = true
		#Show Hunter Particles for Living Chests
		Living = true
		#Show Hunter Particles for Ornate Chests
		Ornate = true
		#Show Hunter Particles for Coins
		Coins = true
		#Show Hunter Particles for Wooden Chests
		Wooden = true
		#Show Hunter Particles for Hardened Chests
		Hardened = true
		#Show Hunter Particles for Enigma Chests
		Enigma = true
		#Show Hunter Particles for Flesh Chests
		Flesh = true
		#Show Hunter Particles for God Altars
		GodAltars = true
		#Show Hunter Particles for Dungeons
		Dungeons = true
		#Show Hunter Particles for Vendors
		Vendors = true
		#Show Hunter Particles for Treasure Doors
		TreasureDoors = true
		#Show Hunter Particles for Pylons
		Pylons = true
		#Show Default White Hunter Particles
		Default = true

	["Client-Only Extensions"."Better Screens"]
		#Improves the Jewel Application Screen
		"Better Jewel Application Screen" = true
		#Improves the Card Deck Screen
		"Better Card Deck Screen" = true

	["Client-Only Extensions"."Gear Roll Colors"]
		#Scrappy+ Gear
		"Scrappy+" = 12369084
		#Common+ Gear
		"Common+" = 5353215
		#Rare+ Gear
		"Rare+" = 16771072
		#Epic+ Gear
		"Epic+" = 16711935
		#Omega Gear
		Omega = 7012096

	["Client-Only Extensions"."Temporal Modifier Timer"]
		#Enable temporal modifier timer overlay
		Enable = true
		#Scale of the text
		#Range: 0.0 ~ 5.0
		Scale = 0.5
		#Horizontal offset
		#Range: -Infinity ~ Infinity
		"X Offset" = 0.0
		#Vertical offset
		#Range: -Infinity ~ Infinity
		"Y Offset" = 6.0

