
["JEI Settings"]
	#Whether to show JEI that is useful for debugging when modding Vault Hunters, this option only controls some added JEI pages, this will hide ones I deem not very useful to the general public. (default: true)
	enableDebugJEI = true
	#Whether to clear VHAPI data out in-between logins to singleplayer worlds or servers, prevent issues with combining different data from servers, also saves some RAM. Note: This breaks VHAPI on LAN, so is disabled by default at the moment.
	clearConfigsOnLogout = false

